### Create the table 'oxcarriertracking

CREATE TABLE `oxcarriertracking` (
`OXID` CHAR( 32 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`OXSHOPID` CHAR( 32 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`OXACTIVE` TINYINT( 1 ) NOT NULL DEFAULT '0',
`OXTITLE` CHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`OXORDER` INT( 11 ) NOT NULL ,
`OXSHORTDESC` TEXT NOT NULL ,
`OXCARRIERICON` CHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`OXTRACKADR` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ,
`OXINSERT` DATETIME NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (`OXID`),
INDEX (`OXSHOPID`,`OXACTIVE`)
) ENGINE = MYISAM ;


### Add OXTRACKADR to oxorder table

ALTER TABLE `oxorder` ADD `OXTRACKADR` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ;