RENAME TABLE `oxcarriertracking` TO `oxcarrier`;

#oxsort
ALTER TABLE `oxcarrier` CHANGE `OXCARRIERICON` `OXICON` CHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxcarrier` CHANGE `OXTRACKADR` `OXCARRIERURL` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxcarrier` ADD `OXTITLE_1` CHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL ;
ALTER TABLE `oxcarrier` ADD `OXSHORTDESC_1` TEXT  NOT NULL ;
ALTER TABLE `oxcarrier` CHANGE `OXICON` `OXICON` VARCHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxcarrier` CHANGE `OXSHORTDESC` `OXSHORTDESC` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL;
ALTER TABLE `oxcarrier` CHANGE `OXINSERT` `OXTIMESTAMP` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `oxorder` CHANGE `OXTRACKADR` `OXCARRIERURL` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL COMMENT 'alternative Url';



/*
Next Line: currently not used
*/
#INSERT INTO `oxconfigdisplay` (`OXID`, `OXCFGMODULE`, `OXCFGVARNAME`, `OXGROUPING`, `OXVARCONSTRAINT`, `OXPOS`) VALUES
#('1ec4235c2aee774aa45d772875437920', 'theme:azure', 'sCarrierIconSsize', 'images', '', 1);

#INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`) VALUES
#('1ec4235c2aee774aa45d772875437920', 'oxbaseshop', 'theme:azure', 'sCarrierIconSsize', 'str', 0x8064a213b1);

#INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`) VALUES
#('1ec4235c2aee774aa45d772875437920', 'oxbaseshop', 'theme:mobile', 'sCarrierIconSsize', 'str', 0x8064a213b1);

